# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab504cba0d813df66b9051ae81c7d03bc05043b7a8bc47081e6783565295a2bea0964913c0b6bd9a8e7694d2633955003cfb173ef10bcc74d24dfa1092a77324

test:
  secret_key_base: 5355f7d451562c2517d2fa40a1b32c24f2e9ca5be5edba6a99f623b47d6aec2ba8671623c6de030c74b5c1522873f05cfead191ab56e3671391bf36660773369

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
